        - in: query
          name: streams_mode
          required: false
          schema:
            type: string
            enum: [none, summary, full]
            default: none
          description: >
            none    : pas de séries
            summary : calcule temps en zones/decoupling sans renvoyer les séries
            full    : renvoie les séries downsamplées
        - in: query
          name: max_points
          required: false
          schema:
            type: integer
            minimum: 100
            maximum: 10000
            default: 1500
          description: Cap max points par série (streams_mode=full)
        - in: query
          name: compute_decoupling
          required: false
          schema:
            type: boolean
            default: false
          description: Calcule la décorrélation HR si streams disponibles
        - in: query
          name: hrmax
          required: false
          schema: { type: integer, minimum: 100, maximum: 230 }
          description: FC max (bpm) pour le calcul des zones (sinon estimée)
        - in: query
          name: hrrest
          required: false
          schema: { type: integer, minimum: 30, maximum: 120 }
          description: FC repos (bpm) (utile si tu veux imposer Karvonen côté détails)
